[Server]
http_port       = 8080                              # HTTP服务端口
password        = "ydev"                            # 访问密码，不配置就不需要密码
https_port      = -1                                # HTTPS服务端口，-1表示不启用
cert_file       = "/path/to/your/cert.crt"          # 证书文件路径
key_file        = "/path/to/your/key.key"           # 证书密钥文件路径
# template_html = "/path/to/your/index.html"        # 自定义模板文件路径

[PreviewConf]
enable          = "ON"                                            # 是否开启文件预览功能，默认OFF。可选值：ON、OFF
agent           = "onlyoffice"                                    # 预览服务类型，可选值：onlyoffice、kkfileview
server          = "http://localhost:20003"                        # 预览服务地址
type            = ["docx", "xlsx", "pptx", "doc", "xls", "ppt"]   # 预览文件类型

# 配置多个目录，每个目录对应一个FxNode
# [[FileNode]]                                                    # 目录配置
# context_path          = "/"                                     # 访问路径，必须唯一
# dir                   = "/home/yonatan/pkg"                     # 本地路径，必须存在
#     [FileNode.Options]
#     autoindex         = "OFF"                                   # 是否开启目录索引，默认ON。可选值：ON、OFF
#     preview           = "OFF"                                   # 是否开启文件预览，默认ON。可选值：ON、OFF
#     template_html     = ""                                      # 自定义模板文件路径

#############################################################################################################
[[FileNode]]
name                     = "pkg"
context_path             = "/"
dir                      = "/home/yonatan/pkg"

[[FileNode]]
name                     = "apps"
context_path             = "/apps"
dir                      = "/home/yonatan/apps"

[[FileNode]]
name                     = "code"
context_path             = "/code"
dir                      = "/home/yonatan/code"

[[FileNode]]
name                     = "public"
context_path             = "/public"
dir                      = "/home/yonatan/test/public"
    [FileNode.Options]
    autoindex         = "OFF"
    preview           = "OFF"
