[server]
port     = 8080
filepath = "/home/yonatan/pkg"
password = "ydev"
pathname = "/"
https    = { key = "key.pem", cert = "cert.pem" }
# template = "/path/to/your/index.html"

[onlyoffice]
server = "http://localhost:20001"
